name: Scan Repository with ScanCode.io

on:
  push:
    branches:
      - master

jobs:
  download-repo-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Archive
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the entire history is fetched
      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: repository-archive
          path: .

  scan-repository:
    runs-on: ubuntu-22.04
    needs: download-repo-archive
    steps:
      - name: Download Repository Archive
        uses: actions/download-artifact@v2
        with:
          name: repository-archive
          path: .

      - name: Run ScanCode.io pipeline
        uses: nexB/scancode-action@alpha
        with:
          pipelines: "scan_codebase"
          input-urls: "repository-archive.zip"
          # Other inputs as needed
