name: Download Repository Archive

on:
  push:
    branches:
      - master  # Adjust this to match your branch

jobs:
  download-repo-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository Archive
        run: |
          # Download the ZIP archive of the repository from the archive URL
          curl -sLO "https://github.com/${{ github.repository }}/archive/master.zip"

      - name: Unzip Repository Archive
        run: unzip -q main.zip -d repo

      - name: Display Repository Structure
        run: ls -R repo
