name: Download Repository Archive

on:
  push:
    branches:
      - master  # Adjust this to match your branch

jobs:
  download-repo-archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
