name: Create Release Notes

on:
  release:
    types: [published]

jobs:
  create_release_notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: master

      - name: Prepend release notes to CHANGELOG.rst
        run: |
          version="${{ github.event.release.tag_name }}"
          body="${{ github.event.release.body }}"
          if [ -n "$body" ]; then
            # Prepend release notes
            printf "%s\n=====================================\n%s\n\n$(cat CHANGELOG.rst)" "$version" "$body" > temp && mv temp CHANGELOG.rst
            echo "Release notes for version $version prepended to CHANGELOG.rst."
          else
            echo "Error: Release notes body is empty."
            exit 1
          fi

      - name: Commit and push release notes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add release notes for version ${{ github.event.release.tag_name }}"
