name: Create Release Notes

on:
  release:
    types: [published]

jobs:
  create_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract release information
        id: extract_release_info
        run: |
          echo "::set-output name=version::${{ github.event.release.tag_name }}"
          echo "::set-output name=body::${{ github.event.release.body }}"

      - name: Create release notes file
        run: |
          version=${{ steps.extract_release_info.outputs.version }}
          body=${{ steps.extract_release_info.outputs.body }}
          echo "$body" > "Release_Notes_$version.md"
          echo "Release notes for version $version generated."

      - name: Commit and push release notes file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate release notes for version ${{ steps.extract_release_info.outputs.version }}"
