name: Create Release Notes

on:
  release:
    types: [published]

jobs:
  create_release_notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: master  # Use 'main' branch instead of 'master'

      - name: Prepend release notes to CHANGELOG.rst
        run: |
          version="${{ github.event.release.tag_name }}"
          body="${{ github.event.release.body }}"
          if [ -n "$body" ]; then
            # Use Python script to prepend release notes
            python3 - <<EOF
with open('CHANGELOG.rst', 'r') as file:
    changelog_content = file.read()

release_notes = "${body}"
release_version = "${version}"

new_changelog_content = f"{release_version}\n=====================================\n{release_notes}\n\n{changelog_content}"

with open('CHANGELOG.rst', 'w') as file:
    file.write(new_changelog_content)
EOF
            echo "Release notes for version $version prepended to CHANGELOG.rst."
          else
            echo "Error: Release notes body is empty."
            exit 1
          fi

      - name: Commit and push release notes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add release notes for version ${{ github.event.release.tag_name }}"
