name: Create Release Notes

on:
  release:
    types: [published]

jobs:
  create_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract release information
        id: extract_release_info
        run: |
          version="${{ github.event.release.tag_name }}"
          body=$(echo "${{ github.event.release.body }}" | sed '1d')  # Remove the first line (Full Changelog)
          echo "version=$version" >> $GITHUB_ENV
          echo "body=$body" >> $GITHUB_ENV
          
      - name: Create Release Directory
        run: mkdir -p release_notes
        
      - name: Create release notes file
        run: |
          version="${{ env.version }}"
          body="${{ env.body }}"
          touch "release_notes/$version.md"
          echo "$body" > "release_notes/$version.md"
          echo "Release notes for version $version generated."

      - name: Commit and push release notes file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate release notes for version ${{ env.version }}"
