name: Create Release Notes

on:
  release:
    types: [published]

jobs:
  create_release_notes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: master  # Use 'main' branch instead of 'master'

      - name: Append release notes to CHANGELOG.rst
        run: |
          version="${{ github.event.release.tag_name }}"
          body="${{ github.event.release.body }}"
          if [ -n "$body" ]; then
            echo -e "\n$version\n=====================================\n$body\n" >> CHANGELOG.rst
            echo "Release notes for version $version appended to CHANGELOG.rst."
          else
            echo "Error: Release notes body is empty."
            exit 1
          fi

      - name: Commit and push release notes to repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add release notes for version ${{ github.event.release.tag_name }}"
